# Generated by Django 4.0.3 on 2022-07-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
