# Generated by Django 4.0.3 on 2022-07-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_visit',
        ),
    ]
