# Generated by Django 4.0.3 on 2022-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
